### ISSUE TITLE
Button caption text confusing when button placed in application panel

### ISSUE THREAD

**Issue by Gitoffthelawn** [rNeomy/javascript-toggle-on-and-off#11]
The text gets truncated, so always reads "Javascript Toggle On".

**Comment by rNeomy** [comment]
What is your OS? Can you provide an screenshot?

**Comment by Gitoffthelawn** [comment]
Test OS is Windows 7.  With Firefox 57, there is no longer a modifiable application panel.  However, when the toolbar button is pinned to the new Overflow Menu, the text is merged together like this:

`Javascript Toggle On and OffJavascript Disabled`

May I recommend a replacing the tooltip text to simply: "Click to enable Javascript" or "Click to disable Javascript" (depending on the status).  Or even more simple: "Enable Javascript" or "Disable Javascript".

For an example, see:
https://addons.mozilla.org/firefox/addon/css-toggler/
https://github.com/quailiff/toggle-css/

Thanks!

**Comment by rNeomy** [comment]
"Click to enable Javascript" and "Click to disable Javascript" seem good to me. Thanks for the report.

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thanks for the great extension!
