### ISSUE TITLE
Reload doesn't restore JS - need to SHIFT-Reload

### ISSUE THREAD

**Issue by deant** [rNeomy/javascript-toggle-on-and-off#14]
FF57 x64 on Windows 10 x64:

When JS is off, turning it back on doesn't work (neither with a manual reload, nor with the "auto-reload-on-toggle" feature) until you manually perform a SHIFT-reload.  Note that going the other way (turning JS off when it's on) works correctly (oddly!).

Since the "auto-reload-on-toggle" doesn't SHIFT-Reload, it is broken in this case.

This happens on site:     http://tools.add0n.com/check-javascript.html

**Comment by rNeomy** [comment]
Thanks for the report. It is fixed now on the dev version.
