### ISSUE TITLE
Feature Request - Hot-key

### ISSUE THREAD

**Issue by UserMcUser** [rNeomy/javascript-toggle-on-and-off#17]
I used to use QuickJS before Firefox ditched legacy add-ons and this one seems to be as close to that add-on as I can find at the moment. Anyway, QuickJS used "Ctrl + Q" as a hot-key to toggle Javascript on/off which was very useful to me.

Would it be possible to add support for a hot-key with this add-on?

**Comment by rNeomy** [comment]
> this one seems to be as close to that add-on as I can find at the moment

What else is missing?

> QuickJS used "Ctrl + Q" as a hot-key to toggle Javascript on/off which was very useful to me.

Is Ctrl + Q free! It is possible to define one, but since Firefox does not yet support customizing the shortcut we need to find something that is not been registered!

**Comment by UserMcUser** [comment]
Well one thing it's missing is a hot-key. ;)

Ctrl + Q does not appear to do anything in the baseline Firefox (as far as I can tell.)

**Comment by andy-portmen** [comment]
> Also realized that old QuickJS did not reload the page when toggled

We have an option for this!

**Comment by rNeomy** [comment]
So for Firefox, the default keyboard shortcut is "Alt+Shift+L" (as of version 0.2.2). That "Ctrl + Q" is not working on Mac OS. For other browsers, the user can define the shortcut and hence there is no default value.

**Comment by UserMcUser** [comment]
Hate to be a bother but could we get a different hotkey, one that's on the left side of the keyboard? Might I suggest using "X" in place of "L"?

It used to be possible for me to unpack and edit a plugin's XPI file to make this sort of change myself but since Mozilla now **requires** XPIs to be signed my efforts would be pointless. 

Cheers!
