### ISSUE TITLE
Invisible icon with dark theme

### ISSUE THREAD

**Issue by mtwwstj9** [rNeomy/javascript-toggle-on-and-off#5]
Hi,I'm glad to find simple but useful extension.

You can see invisible icon with Firefox "Compact Dark" theme.
I think not a little Chrome and Opera user with dark theme,too.

**Comment by rNeomy** [comment]
Thanks for the report. The WebExtension version 0.1.7 fixes this issue;
https://addons.mozilla.org/en-US/firefox/addon/javascript-toggler/
